### ISSUE TITLE
True audio only for both VOD and Live

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#123]
**Describe the bug**
When user turns on audio only on live, video is still being loaded in the background for Android

**Expected behavior**
Only audio of streaming is loaded and that data usage is largely reduced

**Comment by andreasgangso** [comment]
![image](https://github.com/bcc-code/bcc-media-app/assets/727125/6c33ebe3-07c9-47fd-9a4a-aff6e9f37e00)

Switches from 1080p (video_6) to 180p (video_1)
