### ISSUE TITLE
Update google playstore app screenshots on next release

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#124]
[Figma design](https://www.figma.com/file/fWS1tz7FHEHfRqwZbnUmy9/BCC-Media-%E2%80%93-Marketing?node-id=2707%3A74533&t=TS5t9Lg7KQdqopht-1)

**Comment by andreasgangso** [comment]
Done. Will be reviewed by play store together with the v4.4.4 release
