### ISSUE TITLE
Add uservoice to profile page for BCC members

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#125]
**User story**
As a user I want to be able to give feature suggestion

**Acceptance criteria**
1. User are able to see "Suggest a feedback" in the same grouping as  "Contact support"
2. Only BCC members are able to see the uservoice tab
3. The uservoice tab links user to uservoice.bcc.no
4. Auto login to uservoice with profile from bccm app

**Comment by andreasgan** [comment]
Done in #114
