### ISSUE TITLE
Wrong episode release date

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#126]
**Describe the bug**
Episode release date of last episode within show is being shown as release date for every episode

**Expected behavior**
Each episode should show its own release date

This only occurs in app

![photo_2023-03-01 10 01 49](https://user-images.githubusercontent.com/88234679/235922975-b266b73b-4654-4fe9-b04b-e823d3801196.jpeg)

**Comment by andreasgangso** [comment]
Fixed in 4.4.4
