### ISSUE TITLE
Android- Unable to load app

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#131]
Eternally loading on launch for Android

Hei, jeg har satt opp en ny smarttelefon (Samsung S23+). Dessverre kan jeg ikke åpne BCC Media-appen der. bmm osv fungerer fint. hva kan årsaken være? 

DeviceSM-G986B
Environment overridenull
Manufacturersamsung
Operating System
Android 13
Screen Size2400x1080
App Version4.2.7+2300040

https://projects.bcc.no/desk/tickets/10481361/messages
https://projects.bcc.no/desk/tickets/10485982/messages

**Comment by andreasgan** [comment]
was fixed in 4.3.7
