### ISSUE TITLE
Kids- Feedback gathering

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#168]
As I user, I want to easily contact support or provide feedback within the app, so I'm more likely to give feedback

Description:
A tab in setting page for users to write us 

Acceptance criteria:
1. Parental gate
2. Box for users to put down their email, name and message
3. Feedback after submission notifying user message is sent and we will get in touch soon

**Comment by andreasgangso** [comment]
@mulundapm 

**Suggestion**
I think we should include a checkbox to "include device info", which is enabled by default.
Like:

- [x] Include device data for better support. [Click to see data](#).

"Click to see data" opens this in a dialog:

![Image](https://github.com/bcc-code/bcc-media-app/assets/727125/c331d4fb-89af-43ee-b4f8-277059965193)

**Comment by andreasgangso** [comment]
Made a suggestion here https://www.figma.com/file/BMXWzaA93qm8jXKjyPiFOs/BCC-Media-%E2%80%93-Mobile-App-V4?type=design&node-id=9780-55700&t=n7Nq8bEVu7f7vJtN-0

**Comment by andreasgangso** [comment]
The support email mutation is now open for anonymous users.

**Comment by mulundapm** [comment]
Sorry for missing this as description. But would want the mail to reach hello@biblekids.io instead of support@bcc.media

**Comment by fredrikved** [comment]
Can be defined per application group.
