### ISSUE TITLE
UI indicator on play next/ auto play next

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#169]
As a user, I want to be notified that video will autoplay next soon, so that I can response to it accordingly

Acceptance requirement:
1. Countdown starts 5s before video starts
2. User can click play next or wait 5s for next video to start playing
3. Next video should play in same state as current state

![Image](https://github.com/bcc-code/bcc-media-app/assets/88234679/092cc463-6cac-4219-a5d7-46aa4f5ee215)

**Comment by andreasgangso** [comment]
@eliezerben can you make the button here as a flutter component? I'll look into if we can get a flutter overlay on the fullscreen player

**Comment by andreasgangso** [comment]
Done in https://github.com/bcc-code/bcc-media-app/commit/b809a46736f0ec234a0838ea80a23a986fdf7735

**Comment by mulundapm** [comment]
I dont see any UI element indicating it will play next. Do you have a screenshot of what it looks like?
