### ISSUE TITLE
Auto rotation to full screen when rotating to landscape on player page

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#174]
As a user, I want player to be in landscape mode when I orient my device horizontally. 

Acceptance requirement:
1. Orientation lock applies
2. Allow the user to rotate the device to switch between portrait and landscape orientations only in playing state
3. Once the player enters full-screen mode, it should remain in that state until the user explicitly exits or rotates the device back to portrait orientation

**Comment by andreasgangso** [comment]
The main paint point here is that kids aren't figuring out how to go fullscreen.
So we hotfixed this in bible kids v4.4.6 (#175) by going fullscreen as soon as you hit "play".

**Comment by andreasgangso** [comment]
The auto rotation stuff is kinda hard because we want to force portrait for flutter, force landscape in fullscreen, which complicates things. Plus, orientation lock doesn't have an API so we can't even use a simple solution with accelerometer/gyroscope - we **have** to use the native UI orientation stuff to respect the orientation lock.

**Comment by andreasgangso** [comment]
https://github.com/bcc-code/bcc-media-app/tree/feat/fullscreen-on-rotate

**Comment by andreasgangso** [comment]
Since we rotate automatically on play already and we are working on a redesign this will likely be waste of efforts if I do it this week, no? @mulundapm

**Comment by mulundapm** [comment]
If we include rotate automatically on play in bccm, then this task is not needed

**Comment by andreasgangso** [comment]
> If we include rotate automatically on play in bccm, then this task is not needed

You can enable it for bcc media by enabling `auto-fullscreen-on-play` in unleash.
It only affects bcc media because its hardcoded to be enabled for kids
