### ISSUE TITLE
Calendar shows as no tvguide entry during pinsestevnet

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#186]
Description:
"There are no events showing up in the calendar of the BCC Media app. I first noticed this a week or so ago. A few days ago, I updated to the most recent version, which didn't solve the issue."
"Hi—my BCC Media app shows no LIVE transmissions today (5/27) or tomorrow. Will there be any LIVE transmissions this weekend?"

Device info:
iOS 16.5 // 4.4.4+2300063
Android 13 // 4.4.4+2300063

https://projects.bcc.no/desk/tickets/10497862/messages
https://projects.bcc.no/desk/tickets/10497787/messages

**Comment by mulundapm** [comment]
Hi, is this fix released?

**Comment by andreasgangso** [comment]
v4.4.9 has this and I'm sending it to review for bcc media now.
