### ISSUE TITLE
Kids: Persistent anonymousId

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bcc-media-app#192]
**New description**
- [x] Update to rudder_sdk_flutter ^2.5.0
- [x] Use the new `collectDeviceId` option
- [x] Remove our fork

**Old description**
~~With Bible Kids v4.4.8 which has [this change](https://github.com/andreasgangso/rudder-sdk-android/commit/ef8d0919d196d2e9e39cbdd354410294d88e26d0), anonymousId is no longer based on the persistent android deviceId. Which means it's going to be a random ID per app launch.~~

~~Therefore the app needs to generate an ID, persist it (clear it on login if we implement that). As far as I understand, this should pass through compliance because it's not a device identifier, more like an installation id, but this also needs to be validated.
The ID might make sense to be an ID for the kid's profile.~~

**Comment by mulundapm** [comment]
For kids, i havent been using anonymous ID and user ID but rather do analysis based on RS session ID. But would appreciate to have this so that I could start doing analytics based on "installation". From what I understood, if it doesnt recognise a user over time across difference services then it should be fine.

**Comment by andreasgangso** [comment]
it's would also increase accuracy of "daily active users"

**Comment by andreasgangso** [comment]
https://github.com/rudderlabs/rudder-sdk-android/issues/230

**Comment by mulundapm** [comment]
pending on rs

**Comment by andreasgangso** [comment]
Pending specifically on https://github.com/rudderlabs/rudder-sdk-android/pull/281

**Comment by andreasgangso** [comment]
Now pending on https://www.github.com/rudderlabs/rudder-sdk-flutter/issues/119

**Comment by andreasgangso** [comment]
From v4.7.0

**Comment by mulundapm** [comment]
Is the release of 4.7.0 pending on anything?
