### ISSUE TITLE
Refactor the custom grid widget to use a simpler solution

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bcc-media-app#197]
See discussion:
https://github.com/bcc-code/bcc-media-app/pull/196#discussion_r1223188399

Use an existing component like GridView or Table if possible.
If no existing widgets are practical, we can at least simplify the GridRow by calculating the column widths ourselves.

**Comment by eliezerben** [comment]
#198 Used LayoutBuilder to simplify GridRow.
Tried to use the Table widget but it requires at least equal amount of work as the CustomGridView to get it working.
- The table widget takes list of TableRow as children. So we still need to split the items into chunks.
- Each row needs to have the same number of columns. So we still need to add empty widgets to fill the last row.
- Doesn't look like there is a good way to add gap between cells.
