### ISSUE TITLE
Empty episode list when section is poster grid

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#203]
When a show from poster grid is selected, the episode list under the player is empty. 4.5.0. This doesnt occur on other display type

https://github.com/bcc-code/bcc-media-app/assets/88234679/50481642-fcfb-4f42-8f94-26049e6f3bb4

**Comment by eliezerben** [comment]
Tested on two android devices and an iPhone. Not able to reproduce the issue.
