### ISSUE TITLE
Kids- Cable game adjustment

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#206]
- [x] Remove time countdown
- [x] Full screen cable box to fill the web component within app
- [x] Improve performance to minimise lagging
- [x] Game instruction

Potential game instruction:
- Prompt users to click on switch or drag cable on both side
- A instruction screen to show tutorial looping gif

**Comment by mulundapm** [comment]
![247956838-754e6059-98d4-4fc7-8200-88599cde9b5c](https://github.com/bcc-code/bcc-media-app/assets/88234679/3119eedb-db4b-4399-8bad-1ee1be2e0502)

**Comment by andreasgangso** [comment]
Scaling it based on the device isn't so straight-forward because of how it works right now and I may need to change a bunch.
Possibly 1-2 hours to be realistic, so maybe downprioritize..

**Comment by andreasgangso** [comment]
Sizing is better now and released


![Image](https://github.com/bcc-code/bcc-media-app/assets/727125/64289ca7-a1b6-4ddc-bd45-a878a8d0a5d6)
