### ISSUE TITLE
Flutter player MVP finalization

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#212]
Bugs

- [x] Line at the bottom on iPhone fullscreen (https://github.com/bcc-code/bcc-media-app/commit/dce7bdcd4c68be4a1f9bfcb0a0b3439affd0cfa4)
- [x] Picture in picture - returning to the app should not open native player controls (android only) (https://github.com/bcc-code/bcc-media-app/commit/5a6d285bcb69327aa16c0100ea1a029110ae3bcb)

**Comment by andreasgangso** [comment]
v4.5.4.
