### ISSUE TITLE
Simon says fix

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bcc-media-app#229]
No audio

**Comment by andreasgangso** [comment]
@mulundapm

**Comment by mulundapm** [comment]
There are 2 main issue that needs to be addressed before releasing. 

1. The audio is not always playing, as attached video. 
2. The game freezes from time to time, 50% of the time. When it does, screen record crashes as well. 

https://github.com/bcc-code/bcc-media-app/assets/88234679/3cc833cc-e7f4-4575-a5e7-91455e0f9d95

**Comment by andreasgangso** [comment]
I think I've fixed this partially on the game side (i dont think it freezes anymore at least).
This should be fully fixed in v4.5.8 ([commit](https://github.com/bcc-code/bcc-media-app/commit/9dcc4a97f05ba85612c4ff83414dd5fcd08d9f0d))
