### ISSUE TITLE
Translation missing in crowdin

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#232]
These strings are not available in crowdin

![Image](https://github.com/bcc-code/bcc-media-platform/assets/88234679/b756f133-6784-4793-ae4c-6b0cab19de88)

**Comment by andreasgangso** [comment]
Fixed in https://github.com/bcc-code/bcc-media-app/commit/54e8b5767c7bb3ae0479616fb3724abbd763c36b
