### ISSUE TITLE
Cast receiver for bible kids

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bcc-media-app#243]
The bible kids app should have its own cast receiver with bible kids' logo etc.
Also, the way it is now, you can open a video in bcc media, then open bible kids and it will show in the mini player there too..

**Comment by andreasgangso** [comment]
Has its own receiver/appId now from v4.6.5 but its not customized.

**Comment by andreasgangso** [comment]
I'd wait for the app redesign to ensure the vibe is the same

**Comment by mulundapm** [comment]
sp?

**Comment by andreasgangso** [comment]
2

**Comment by andreasgangso** [comment]
Because we included actual casting from the device as well, this ended up a bit bigger. Maybe 3sp.

**Comment by andreasgangso** [comment]
v5.0.8
