### ISSUE TITLE
Fix missing rudderstack events on iOS

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bcc-media-app#244]

**Comment by andreasgangso** [comment]
seems to have started 4.6.1

![Image](https://github.com/bcc-code/bcc-media-app/assets/727125/33cb7b1e-28c8-45b8-83db-16e7acca8c90)

**Comment by andreasgangso** [comment]
https://github.com/rudderlabs/rudder-sdk-flutter/issues/116

**Comment by mulundapm** [comment]
Not sure if its related, but the total count of Bible Kids application_install event has been decreasing day by day. 2 days ago was 2880, yesterday was 2850 and today went down to 2810. Not sure how application_install is triggered but total count should only be increasing right?

https://metabase.bcc.media/question/477-bible-kids-app-download

**Comment by andreasgangso** [comment]
The root cause here seems to be that the newer rudder sdks are sending gzipped payloads, which our self-hosted rudderstack  is rejecting because we are still on a very old version.
@KillerX needs to update to the latest (1.12.2)

**Comment by andreasgangso** [comment]
We're now on rudder-server v1.12.2 so you should see events start rolling in the next few hours @mulundapm. The devices should be sending the missing data from the last few days too. (so remember to use "original timestamp")

**Comment by mulundapm** [comment]
Will create another issue for Matjaz to create views that include more data
