### ISSUE TITLE
BCCM Live on AndroidTV

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#245]
Support BCC Media Live stream on AndroidTV

**Acceptance criteria:**

- Log in with QR code
- Log out
- Start the live stream
- Select audio and subtitle languages

- [x] Changing the banner
- [x] Cursor
- [x] Getting reviewed and approved

**Comment by andreasgangso** [comment]
Acceptance criteria:

- Log in with QR code
- Start the live stream
- Select audio and subtitle languages

Correct?

I want to suggest that we call it "BCC Media Live", to make it obvious it's a limited version

**Comment by mulundapm** [comment]
Use should be able to log out too

**Comment by mulundapm** [comment]
https://www.figma.com/file/fWS1tz7FHEHfRqwZbnUmy9/BCC-Media-%E2%80%93-Marketing?type=design&node-id=8038-150761&mode=design&t=nXkDwEPkzGGAXniA-0 Banner ready

**Comment by mulundapm** [comment]
Hi, are event from AndroidTV available in metabase?

**Comment by andreasgangso** [comment]
I checked and there's no good way to differentiate. And we're also not sending events for the new routes.
