### ISSUE TITLE
Kids v2: Language settings

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bcc-media-app#263]
Includes

- [x] Player support for multiple languages
- [x] App language settings
- [ ] Ordering / Prioritization UI

**Comment by andreasgangso** [comment]
@mulundapm this was a wrong estimate because i forgot some details.
Need to implement some extra stuff on the player side. So 5 sp is more correct

**Comment by mulundapm** [comment]
Its a learning then. Will have to keep it at a 2 and take it up at retro.
