### ISSUE TITLE
Chronological order of chapters

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#277]
Make orders of chapter chronological

![Image](https://github.com/bcc-code/bcc-media-app/assets/88234679/3a1efb61-bc67-4ca4-8f0c-da05e410e682)

Definition of done: when its confirmed in the app that it has correct order for https://app.bcc.media/episode/1859

**Comment by mulundapm** [comment]
@andreasgangso @fredrikved The order doesnt get sorted in app. Will have to really confirm it will work before we set 0 points, or we should only set 0 to lists.

**Comment by mulundapm** [comment]
This is something we have to address before høstcamp

**Comment by fredrikved** [comment]
Still took only 5 minutes to fix.

**Comment by mulundapm** [comment]
The chapters are still not in the correct order. Please set this as done when its confirmed in the app that it has correct order for https://app.bcc.media/episode/1859 @fredrikved

**Comment by fredrikved** [comment]
Still done.

Deployment failed.
