### ISSUE TITLE
Android notifies users that the app crashes often

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#300]
Users are getting notification from android that bcc media app crashes frequently. Janna also experienced the same. Will have to investigate the root cause of this and fix it. 

Needs also confirmation that this will not occur for BibleKids app

![Image](https://github.com/bcc-code/bcc-media-app/assets/88234679/aedc23f1-638d-4710-a308-f2d4de9d939f)

![Image](https://github.com/bcc-code/bcc-media-app/assets/88234679/693457ef-1786-4299-b066-038b072ccdac)

**Comment by andreasgangso** [comment]
ah yea would be especially smart to fix this before everyone starts putting it in "deep sleep mode" as the screenshot suggests

**Comment by andreasgangso** [comment]
Last time I checked I think this was related to https://github.com/androidx/media/issues/167 / https://github.com/androidx/media/issues/111

needs a proper investigation though

**Comment by andreasgangso** [comment]
<img width="613" alt="Screenshot 2023-11-13 at 12 24 51" src="https://github.com/bcc-code/bcc-media-app/assets/727125/7c9b9cd0-b0c1-4902-b126-37b8d073171e">

So this should be prioritised next sprint

**Comment by andreasgangso** [comment]
![Image](https://github.com/bcc-code/bcc-media-app/assets/727125/c1510f25-5b21-4fb4-88f8-4d907dfa1d4c)

**Comment by andreasgangso** [comment]
For the record this was mostly a bug introduced with downloads that caused this for both bcc media and bible kids on android.
Should be fixed in BK 5.1.1 and BCCM 5.0.0

**Comment by andreasgangso** [comment]
No error reports on bk 5.1.1 and bccm 5.0.0 so im going to set minimum versions to these. But I need to wait a couple of days because I forgot to release these on iOS.

**Comment by mulundapm** [comment]
Is this done?
