### ISSUE TITLE
Live tab in app during transition period

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#336]
3 different states in BCC Media app during transmission period.

Functional live in live tab
Directory to connect app/ app store in live tab
Disable live tab
Versions released during transition period (jan- after easter) should be able to handle all 3 states behind feature flag

After Easter, only accommodate state 3

**Comment by andreasgangso** [comment]
`force-bcc-live` (state 2)
`remove-live-tab` (state 3)
