### ISSUE TITLE
Expired tokens on shorts

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#340]
Unclear how to reproduce it

Feedback from an user via in-app survey (no device info):
![Image](https://github.com/bcc-code/bcc-media-app/assets/88234679/cda186d6-e805-4bcd-9751-9afba99a899c)

![Image](https://github.com/bcc-code/bcc-media-app/assets/88234679/fcc4cd83-3dcf-458c-93f5-c34af491c1cf)

**Comment by andreasgangso** [comment]
I think the gray play sign is expired tokens. so if you reopen the app after backgrounding it for 6 hours this will happen.
if you scroll far enough it should resolve but yea we need to fix this.

About "glitches a lot", i have no idea
