### ISSUE TITLE
Shorts should not go into PIP when exiting app

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#348]
Repro:
1. Open shorts
2. pause shorts
3. Play shorts
4. Swipe up to leave app

Expected: Video pauses and no PIP
Reality: Pip of shorts

iOS version 5.3.3

Edit:
Tested now on 04. sept,
repro steps:
- Open shorts
- Swipe up to leave app
- short goes in pip

**Comment by sifferhans** [comment]
https://github.com/bcc-code/bccm-player/pull/70

**Comment by sifferhans** [comment]
https://github.com/bcc-code/bcc-media-app/pull/430
