### ISSUE TITLE
Stop other playbacks when video has started playing

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#350]
Currently users are able to play BMM and BCCM at the same time. 

Starting a play in BCCM (VOD, shorts) should stop other playbacks from other app. 

Repro:
1. Open bmm on iOS and play a track
2. Open bccm and play a vod

Expected: bmm stops play
Reality: bccm plays on top of bmm

**Comment by andreasgangso** [comment]
Will be in next release
