### ISSUE TITLE
Continue scrolling when open short from link

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#362]
Currently when users open shorts from section/ share link, users will have to click back to continue browse short.

ideal case would be continue scrolling from the opened short

https://github.com/bcc-code/bcc-media-app/assets/88234679/2ed6c5fd-38eb-4e67-96c5-c30f1fb00b6b

**Comment by andreasgangso** [comment]
WILL BE IN v5.3.9

:)

**Comment by andreasgangso** [comment]
and im waiting for contributors before i push 5.3.9
