### ISSUE TITLE
Show content type pills in contributions (frontend)

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bcc-media-app#379]
- Analytics on chapters being clicked under contribution
- Overflow of names more than 2 lines (smaller font and support 3 lines of text)

**Comment by andreasgangso** [comment]
> Directus chapter	Mediabanken chapters
> Song	sang
>  	musikkvideo
> Sing along	singalong
> Speech	tale
>  	vitnesbyrd
>  	appelle
> Interview	panel
>  	intervju
> Temafilm	kortfilm
>  	anslag
>  	temafilm
>  	animasjon
> Others	rest of the types
> 1. Panel should be shown within an "Interview" pill according to this, but it is current under "other" in the app. Noticed that the key for panel in MB is "panel" and value is "Panelsamtale". could it be the reason it is in the wrong group?
> 2. Tale and Vidnesbyrd should be grouped as "Speech" but currently are shown as separate pills
> 3. Notice the pills are mix of english and norwegian. What is the original language for those?

1 and 2 is addressed, was the wrong mapping
3.. The pills are translated via "Phrases" in admin (synced with crowdin as always). The original is norwegian. But was missing some, added them now.

**Comment by mulundapm** [comment]
point 2 is still occurring for the latest prod
