### ISSUE TITLE
Auto replay on shorts

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#390]
Currently the video ends at first frame when user completes a short. It should replay appoint completion

**Comment by andreasgangso** [comment]
cant reproduce anymore, note down which short this happens on if it happens again

**Comment by andreasgangso** [comment]
I think ive fixed this in 5.5.7

**Comment by mulundapm** [comment]
until contribution is in prod

**Comment by mulundapm** [comment]
This was fixed in 5.5.7 but unfortunately proceeds on 5.6.1
