### ISSUE TITLE
Contributors doesnt land on correct timestamp

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#398]
Repro:

1. Open Gershon Twilley in contributors
2. Click "Ungdomstevnet i India"

Expected: player starts at the beginning of chapter, which is 01:17:52
Reality: player starts at the beginning of episode, 00:00

Reproducible both Android and iOS 5.5.8

Notice it happens to multiple chapters as well

episode 1592

**Comment by andreasgangso** [comment]
> Repro:
> 
> 1. Open Gershon Twilley in contributors
> 2. Click "Ungdomstevnet i India"
> 
> Expected: player starts at the beginning of chapter, which is 01:17:52 Reality: player starts at the beginning of episode, 00:00
> 
> Reproducible both Android and iOS 5.5.8
> 
> Notice it happens to multiple chapters as well

have you verified that the data is correct in admin?

**Comment by mulundapm** [comment]
data is correct in admin
