### ISSUE TITLE
Show show and season title together with chapter under contributors

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#406]
include season name next to show name
![Image](https://github.com/user-attachments/assets/56e0fd1a-f21f-4656-89b9-20c9e4f82889)

current
![Image](https://github.com/user-attachments/assets/f2565817-e0e6-47f2-b4b8-cbad802934d1)

**Comment by andreasgangso** [comment]
Also moved the title to the top. asked søren about that:


![Image](https://github.com/user-attachments/assets/b7317ef4-1014-406b-8de4-54b88df2de66)
