### ISSUE TITLE
Investigate deeplink issue on Android

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#410]
When users click on short link, it directs users to web instead of app

**Comment by andreasgangso** [comment]
Worked for matjaz and yuri who previously had this issue. so i think it was a bug in an older version.

**Comment by andreasgangso** [comment]
Yea one of the older devices here also had this bug reproducable now.
- it was on 5.4.9
- updated via play store (got v5.6.1)
- problem gone
