### ISSUE TITLE
Show page- app

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#413]
A page for show to display each season as its own section.

if the recently published date of an episode is <7 days within the section, then show list view, else default view. 
Admin should be able to override page when needed

**Comment by andreasgangso** [comment]
> Admin should be able to override page when needed

Not doing this for now :)

**Comment by andreasgangso** [comment]
> > Admin should be able to override page when needed
> 
> Not doing this for now, requires backend changes :)

actually it's quite simple it's just a field on the show level. maybe matjaz can throw it in tomorrow. we'll see

**Comment by mulundapm** [comment]
1. For episodes with publish date in the future are clickable and shouldnt be 
2. [Tilbakeblikk video ](https://admin.brunstad.tv/admin/content/episodes/1289)has the publish date in the future but its marked as New within show page (Not shown in home page)

Example: Påskecamp show


![Image](https://github.c

![Image](https://github.com/user-attachments/assets/a6a99471-1718-4775-8b91-be7ba7a7716a)

om/user-attachments/assets/6c202fa7-02c6-48f6-8bee-ecf8cf8a0b3b)
