### ISSUE TITLE
investigate chromecast issue

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#414]
2 users with chromecast 3 experience issue with stability of casting on VOD

"When using the app and casting, sometimes it will not play, other times it will play for around 30 seconds and then buffer but never continue"

"Chromecast stream completely dies and I need to relaunch from the beginning"

implement loggings on npaw

**Comment by andreasgangso** [comment]
Added sentry to chromecast. Just waiting to see if anything obvious pops up
