### ISSUE TITLE
add 1s delay to startup time

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bcc-media-app#421]
- measurement
  - treatment group vs control group
  - treatment group: first week vs 2nd week

**Comment by sifferhans** [comment]
@kkuepper What group should be tested on? Just 50/50 percentages?

**Comment by sifferhans** [comment]
And btw, is 1s enough of a delay?

**Comment by sifferhans** [comment]
@kkuepper And I should not do anything in the code yet, right? just enable the feature flag for a week, and then add the delay the second week?

**Comment by kkuepper** [comment]
talked about it on zoom

**Comment by sifferhans** [comment]
@kkuepper Didn't create a branch for this, sorry. But here is the commit to be reviewed
https://github.com/bcc-code/bcc-media-app/commit/2887fe86a68c55a7cdda0fdfc93afb8c8c7c1e61

**Comment by kkuepper** [comment]
@mulundapm @sifferhans Who is taking charge of executing the experiment once enough users have updated their app?

**Comment by mulundapm** [comment]
me
