### ISSUE TITLE
make Sentry work for us

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bcc-media-app#422]
- [x] why do we see a lot more crashes?
- [x] how do we get a quick overview if we have problems or if everything looks ok

**Comment by sifferhans** [comment]
@kkuepper 
We should probably separate the different platforms into separate Sentry projects.
I think it makes sense in our case, as we have different versions of the app written in different languages etc.

So instead of every error going into `bcc-media-platform`, we have separate projects like this:
- `bcc-media-flutter`
- `bcc-media-tvos`
- `bcc-media-web`

This will help a lot with tracking and filtering down issues.

Any arguments against it?

**Comment by sifferhans** [comment]
## Crashes vs Errors
We don't seem to see a lot more **crashes** in Sentry; we simply see a lot more events overall. 
Sentry picks up all exceptions and errors, while Crashlytics is more directed towards application crashes and what caused them.

We can configure the level of events to track in Sentry: https://docs.sentry.io/platforms/flutter/configuration/options/#diagnostic-level
Setting this to a higher level might help reduce some noise.

## Browser errors
Based on the issues logged in Sentry, browser errors makes up 23 of the 40 unresolved issues in the `bcc-media-platform` project at the time I am writing this.
**_That is almost 60% of all issues reported; more than tvOS and Flutter combined._**

**Comment by kkuepper** [comment]
projects:
- bccm-mobile
- bccm-tvos
- bccm-web
- live-mobile
- live-tvos
- live-web
- live-androidtv
- kids-mobile
- kids-web
- bmm-mobile
- bmm-web
- chromecast
  - bccm
  - live
  - kids

**Comment by sifferhans** [comment]
@kkuepper The Android TV app is just the Flutter app, which means we probably cannot send TV events to the androidtv Sentry project. At least not easily, since Sentry is initialized at startup while checks for Android TV is done at runtime

**Comment by sifferhans** [comment]
@kkuepper The Live AndroidTV app is just Flutter, so has same errors as the Android app. So I think it will not be necessary with a separate project in Sentry for that.

**Comment by sifferhans** [comment]
Everything is now connected to Sentry, except the BMM apps 🎊
