### ISSUE TITLE
Revert hardcoded delay for short preload

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#441]
investigate potention solutions for "Instant loading" as users scroll, prevent visible loading screen for a more seamless scroll

bccm: 

https://github.com/user-attachments/assets/f4243b80-d7d1-4381-9a40-25ea3fda5f63

insta: 

https://github.com/user-attachments/assets/814d5465-3e9b-4341-968e-c1bb51d669a9

youtube: 

https://github.com/user-attachments/assets/ce55a1f2-62c1-4ad1-93b2-8fa7cebb8b2f

**Comment by sifferhans** [comment]
https://github.com/bcc-code/bcc-media-app/pull/453

**Comment by sifferhans** [comment]
Might also be related to https://github.com/bcc-code/bcc-media-platform/issues/1013

**Comment by sifferhans** [comment]
The shorts view now stutters when scrolling. We should investigate further to find areas to improve speed
