### ISSUE TITLE
Monitor logging of log out event on sentry

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#445]
app version .26 include loggings on logout events on sentry 
iOS released on 17. sept 
Android released on 4. sept

**Comment by sifferhans** [comment]
For some of the errors, I've moved from throwing to just dumping them in the console. This is because they are not errors by definition, and they took a lot of capacity in Sentry

**Comment by sifferhans** [comment]
By the logging in Sentry, I cannot really see anything out of the ordinary, by what I understand
