### ISSUE TITLE
Prevent network errors from going to Sentry

### ISSUE THREAD

**Issue by sifferhans** [bcc-code/bcc-media-app#454]
We should filter out all errors related to network issues, as we have no control over users network. These kinds of issues also use a lot of our monthly capacity in Sentry

The filtering should be implemented in code.

**Comment by mulundapm** [comment]
The noisy errors related to unleash are errors triggered by network problems on the users devices, which we have no control over.

The only thing we can do here is filter out network errors before they get to Sentry

**Comment by sifferhans** [comment]
I've started filtering out events of type `FetchFailure` as well, as they are thrown when images cannot load. They are also the most frequent network errors
