### ISSUE TITLE
Send Rudderstack event that can be linked to a NPAW playback session in Metabase

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#459]
The goal is to have a RS event where we can add arbitrary metadata to the NPAW play session.

We should hook into either NPAW even or some kind of "playback started" event.
We should make sure that every NPAW playback session has _at least_ one corresponding RS event, but can have more than one (just don't send them like every second).

- [x] Android
- [x] ios
- [x] tvos
- [x] web

**Comment by sifferhans** [comment]
@KillerX There is a way to hook into the different events sent to npaw, but I cannot see any unique identifier per event.
I think there is a way to inject custom data into the request before it is sent to npaw, but I haven't found the specific API to do that yet

**Comment by sifferhans** [comment]
https://github.com/bcc-code/bccm-player/pull/75
https://github.com/bcc-code/bcc-media-app/pull/479

**Comment by sifferhans** [comment]
npaw: `transactionCode`
rudderstack: video_played event, `referenceId`

**Comment by mulundapm** [comment]
Testing status:
- [ ] bccm tvOS 
    - No transcriptionCode nor video_played
- [x] bccm web
- [ ] bccm mobile
- [ ] live

**Comment by mulundapm** [comment]
typo :)

**Comment by sifferhans** [comment]
I am blocked from publishing a new version, as the test runner we use in CI is crashing. I'll need to fix that before this is testable

**Comment by sifferhans** [comment]
This should now be testable in the newest test versions
