### ISSUE TITLE
Why do people end up on the login page

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#460]
- clean up logs that are noise
- Send the event to rudderstack
- investigate the logs

**Comment by sifferhans** [comment]
I am now going through the authentication setup in `bccm_core` to understand exactly how it is set up

**Comment by sifferhans** [comment]
I've added some Rudderstack logging everywhere we call the `logout()` function

**Comment by sifferhans** [comment]
Btw @mulundapm this is probably more than 3 story points, as I am going through the authentication system in detail

**Comment by mulundapm** [comment]
pending on release of rs logout log
