### ISSUE TITLE
Analyse network traffic for shorts (bccm, tiktok, instagram)

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#461]
tools
- mitmproxy
- fiddler
- wireshark

**Comment by andreasgangso** [comment]
think you can do this with "Instruments" on ios

**Comment by sifferhans** [comment]
I am writing some notes here as I investigate
https://www.notion.so/bccmedia/Shorts-performance-learnings-115563c0cccf80b0854efffebab6429d?pvs=4
