### ISSUE TITLE
Make sure all platforms send the same 3-letter language code

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#466]

**Comment by andreasgangso** [comment]
for reference: https://gist.github.com/andreasgangso/82d46f0ba5cdbb52cd7b539615050ea0

**Comment by sifferhans** [comment]
https://github.com/bcc-code/bccm-player/pull/74
https://github.com/bcc-code/bcc-media-app/pull/476

**Comment by mulundapm** [comment]
Kids app is ok

Subtitle on bccm-web is still sending english name of language e.g. "Norwegian"
bccm-tvos is not sending content language nor subtitle

will test live after lunch.

**Comment by sifferhans** [comment]
tvOS only sends language codes if the user has set the languages in "settings" screen

**Comment by andreasgangso** [comment]
Why three letter codes @mulundapm @KillerX ?
2 letter is the better to standardize on, ref https://gist.github.com/andreasgangso/82d46f0ba5cdbb52cd7b539615050ea0

**Comment by mulundapm** [comment]
We have languages that are not support in 639-1, e.g. Khasi and Cantonese

**Comment by andreasgangso** [comment]
> We have languages that are not support in 639-1, e.g. Khasi and Cantonese

yes but the thing is that RFC5646/BCP47 supports both, so that doesnt matter. you would just use 639-3 only for these two.

> - Use 2-letter codes from 639-1 first. So you should always use 2 letter codes if possible!
> - If no 2-letter exists, or you need to use 3 letter codes for some reason, 639-3 is the standard (its basically a superset of 639-2/T)).

**Comment by KillerX** [comment]
Because by the end of the day it does not matter as long as it's consistent.

**Comment by andreasgangso** [comment]
> Because by the end of the day it does not matter as long as it's consistent.

almost true, if you werent at the mercy of players like avplayer and chromecast. we had issues with it auto-mapping to something else iirc

but if it works it works 🤷

**Comment by KillerX** [comment]
It's statistics. If we say it works, it works :)
