### ISSUE TITLE
Analyse logout logs from rs

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#470]
add 2 new logs relared to the issue

**Comment by sifferhans** [comment]
Added two new logs based on the type of exception that is thrown

**Comment by sifferhans** [comment]
@mulundapm Should we create a new issue to follow up on this next sprint?

**Comment by mulundapm** [comment]
@sifferhans ios is released and android is on review. You maybe close this when there is a related log coming in.
