### ISSUE TITLE
"Renderbox was not laid out" error reported 31k times in Sentry

### ISSUE THREAD

**Issue by sifferhans** [bcc-code/bcc-media-app#484]
There is an issue currently eating up our monthly error budget. 
https://bcc-media-sti.sentry.io/issues/5666539/?project=4507803304394832&query=is:unresolved%20issue.priority:%5Bhigh,%20medium%5D&statsPeriod=90d&stream_index=1

Could be relevant
https://github.com/flutter/flutter/issues/83481

**Comment by andreasgangso** [comment]
> * we see that the video bitrate is immediately reduced to the lowest quality, which probably means the video player is very small (no size)

bccm_player sets the bitrate to the lowest when you background / audio-only
