### ISSUE TITLE
change flutter_secure_storage iOS config for authentication

### ISSUE THREAD

**Issue by sifferhans** [bcc-code/bcc-media-app#485]
we should do a smooth migration to the new configuration to prevent every user from having to log in at once

**Comment by sifferhans** [comment]
https://github.com/bcc-code/bccm-flutter/pull/7

**Comment by sifferhans** [comment]
Logging in should work as usual

**Comment by mulundapm** [comment]
https://bcc-media-sti.sentry.io/issues/7008601/?project=4507803304394832&query=is:unresolved%20issue.priority:%5Bhigh,%20medium%5D%20%22user%20interaction%22&statsPeriod=30d&stream_index=0

**Comment by KillerX** [comment]
On android the upgrade was seamless.

**Comment by mulundapm** [comment]
from vej .45
