### ISSUE TITLE
Feature flag: look for alternatives/ invest more into unleash

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#492]
Make decision on whether we should go for another alternatives for feature flag or to implement unleash correctly

**Comment by sifferhans** [comment]
Some popular alternatives
- [Launchdarkly](https://launchdarkly.com/compare/launchdarkly-vs-unleash/)
- [Statsig](https://www.statsig.com/featureflags)
- [Growthbook](https://www.growthbook.io/)
- [PostHog](https://posthog.com/feature-flags)

**Comment by sifferhans** [comment]
We have just updated Unleash to the newest available version

**Comment by sifferhans** [comment]
The feature flags are fetched correctly from the local cache before the app is fully initialized, but the app is not using them correctly when getting the front page

I am gonna try to override the `appConfigProvider` in the app, and see if I can make the frontpage initialization get the feature flags
